# Model arguments
# model_name_or_path: 
model_name_or_path: /path/to/deepseek-math-7b-warm
model_revision: main
torch_dtype: bfloat16
attn_implementation: flash_attention_2

# Data training arguments
dataset_name: DigitalLearningGmbH/MATH-lighteval
dataset_config: default
dataset_prompt_column: problem

eval_dataset_name: HuggingFaceH4/MATH-500
eval_dataset_config: default
eval_dataset_split: test

system_prompt: "Please reason step by step, and put your final answer within \\boxed{}."

# GRPO trainer config
bf16: true
use_vllm: true
vllm_mode: colocate
vllm_gpu_memory_utilization: 0.3
do_eval: true
eval_strategy: "steps"
eval_steps: 10
gradient_accumulation_steps: 1
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false
learning_rate: 1.0e-06
log_completions: false
log_level: info
logging_first_step: true
logging_steps: 1
logging_strategy: steps
lr_scheduler_type: constant_with_warmup
max_prompt_length: 512
max_completion_length: 1024
max_steps: -1
num_generations: 8
num_train_epochs: 2
output_dir: checkpoints/deepseek-math-7b-warm_MATH-lighteval_GRPO
overwrite_output_dir: true
per_device_eval_batch_size: 32
per_device_train_batch_size: 32
push_to_hub: false
hub_model_id: deepseek-math-7b-warm_MATH-lighteval
hub_strategy: every_save
report_to:
- swanlab
reward_funcs:
- accuracy
reward_weights:
- 1.0
save_strategy: "no"
save_total_limit: 1
save_only_model: true
seed: 42
warmup_ratio: 0.0